### ISSUE TITLE
embed-environment-variables is not available

### ISSUE THREAD

**Issue by mrtruongminh** [etalab/cra-envs#2]
When running `npx embed-environment-variables` as stated in the Dockerfiles in this repo https://github.com/garronej/cra-envs-demo-app, I got the following error:
![image](https://user-images.githubusercontent.com/28686629/169788487-d29a8ebb-a4be-4d7e-b055-e9db7b70538d.png)

**Comment by garronej** [comment]
Thank you for reporting

**Comment by garronej** [comment]
Hi @mrtruongminh,  
I attract your attention over the fact that you can only run `npx embed-environment-variable` if `cra-envs` is present is installed wether globally or locally.  
When [it is run in the entrypoint](https://github.com/garronej/cra-envs-demo-app/blob/f4c0884f43168186e99eee298d1e032c8f8dd4f8/Dockerfile#L20) it works because it [have been previously installed globally](https://github.com/garronej/cra-envs-demo-app/blob/f4c0884f43168186e99eee298d1e032c8f8dd4f8/Dockerfile#L14).  

If you want to run it in a single line you can do:  
`npx -y -p cra-envs@1.2.6  embed-environment-variables`  

however, be sure to enforce that you use the same version of `cra-envs` in your code (`import { ... } from "cra-envs"`) and when you run `npx embed-environment-variables`.   

Best regards
